version: "3"
services:
  db:
    image: postgres:9.6.8
    restart: always
    environment:
      - PGDATA=/pgdata
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/pgdata
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
      - RAILS_ENV=development
      - SECRET_KEY_BASE
      - EDITOR
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - RAILS_SERVE_STATIC_FILES
      - RACK_ENV
      - OWNER_UNION
      - mailgun_host
      - mailgun_domain
      - mailgun_api_key
      - LANG
      - GA_TRACKING_ID
      - EMAIL_FROM
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_BUCKET
      - AWS_ASSET_URL
      - AWS_ACCESS_KEY_ID
      - AUTHORIZED_BY
      - APP_TITLE
    ports:
      - "$APP_PORT:3000"
    links:
      - db
    volumes:
      - bundle:/usr/local/bundle
      - ./app:/app
    tty: true
    stdin_open: true
    command: ./docker-start
volumes:
  pgdata:
  bundle:
