require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SupergroupsController do

  # This should return the minimal set of attributes required to create a valid
  # Supergroup. As you add validations to Supergroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupergroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all supergroups as @supergroups" do
      supergroup = Supergroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:supergroups).should eq([supergroup])
    end
  end

  describe "GET show" do
    it "assigns the requested supergroup as @supergroup" do
      supergroup = Supergroup.create! valid_attributes
      get :show, {:id => supergroup.to_param}, valid_session
      assigns(:supergroup).should eq(supergroup)
    end
  end

  describe "GET new" do
    it "assigns a new supergroup as @supergroup" do
      get :new, {}, valid_session
      assigns(:supergroup).should be_a_new(Supergroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested supergroup as @supergroup" do
      supergroup = Supergroup.create! valid_attributes
      get :edit, {:id => supergroup.to_param}, valid_session
      assigns(:supergroup).should eq(supergroup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Supergroup" do
        expect {
          post :create, {:supergroup => valid_attributes}, valid_session
        }.to change(Supergroup, :count).by(1)
      end

      it "assigns a newly created supergroup as @supergroup" do
        post :create, {:supergroup => valid_attributes}, valid_session
        assigns(:supergroup).should be_a(Supergroup)
        assigns(:supergroup).should be_persisted
      end

      it "redirects to the created supergroup" do
        post :create, {:supergroup => valid_attributes}, valid_session
        response.should redirect_to(Supergroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supergroup as @supergroup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supergroup.any_instance.stub(:save).and_return(false)
        post :create, {:supergroup => { "name" => "invalid value" }}, valid_session
        assigns(:supergroup).should be_a_new(Supergroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Supergroup.any_instance.stub(:save).and_return(false)
        post :create, {:supergroup => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested supergroup" do
        supergroup = Supergroup.create! valid_attributes
        # Assuming there are no other supergroups in the database, this
        # specifies that the Supergroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Supergroup.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => supergroup.to_param, :supergroup => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested supergroup as @supergroup" do
        supergroup = Supergroup.create! valid_attributes
        put :update, {:id => supergroup.to_param, :supergroup => valid_attributes}, valid_session
        assigns(:supergroup).should eq(supergroup)
      end

      it "redirects to the supergroup" do
        supergroup = Supergroup.create! valid_attributes
        put :update, {:id => supergroup.to_param, :supergroup => valid_attributes}, valid_session
        response.should redirect_to(supergroup)
      end
    end

    describe "with invalid params" do
      it "assigns the supergroup as @supergroup" do
        supergroup = Supergroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supergroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => supergroup.to_param, :supergroup => { "name" => "invalid value" }}, valid_session
        assigns(:supergroup).should eq(supergroup)
      end

      it "re-renders the 'edit' template" do
        supergroup = Supergroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Supergroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => supergroup.to_param, :supergroup => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supergroup" do
      supergroup = Supergroup.create! valid_attributes
      expect {
        delete :destroy, {:id => supergroup.to_param}, valid_session
      }.to change(Supergroup, :count).by(-1)
    end

    it "redirects to the supergroups list" do
      supergroup = Supergroup.create! valid_attributes
      delete :destroy, {:id => supergroup.to_param}, valid_session
      response.should redirect_to(supergroups_url)
    end
  end

end
